edition = "2021"

max_width = 120

reorder_imports = true
reorder_modules = true

use_try_shorthand = true
use_field_init_shorthand = true
merge_derives = true

tab_spaces = 4
hard_tabs = false

newline_style = "Unix"
